const AI_TOOLS = [
  // ── Coding Assistants ──
  {
    id: "claude-code",
    name: "Claude Code",
    category: "cli-tool",
    rating: 4.8,
    trending: true,
    url: "https://github.com/anthropics/claude-code",
    tagline: "Anthropic's agentic coding CLI that lives in your terminal",
    description:
      "Claude Code is an agentic coding tool that lives in your terminal, understands your codebase, and helps you code faster through natural language commands. Powered by Claude Opus 4.6, it handles routine tasks, explains complex code, manages git workflows, and can operate as a multi-agent development platform.",
    whyGood: [
      "Deep codebase understanding with whole-project context awareness",
      "Multi-agent collaboration with Agent Teams for parallel workstreams",
      "Works in terminal, IDE, Slack, and web — no environment switching",
      "Automatic memory recall across sessions for continuity",
      "Sandbox mode for safe execution on Linux & Mac",
      "Enterprise-grade with analytics API, SSO, and managed MCP allowlists",
    ],
    useCases: [
      "Autonomous code generation and refactoring across large repos",
      "Git workflow automation (commits, PRs, branch management)",
      "Debugging and explaining complex legacy codebases",
      "Multi-file editing orchestrated by AI agents",
      "CI/CD pipeline debugging and infrastructure code",
    ],
    tags: ["CLI", "Anthropic", "Multi-agent", "Terminal", "Open Source"],
    stars: "30k+",
    pricing: "API-based (Anthropic credits)",
    lastUpdated: "Feb 2026",
  },
  {
    id: "antigravity",
    name: "Google Antigravity",
    category: "coding-assistant",
    rating: 4.7,
    trending: true,
    url: "https://antigravityai.org/",
    tagline: "Google's agent-first IDE powered by Gemini 3",
    description:
      "Google Antigravity is an AI-powered IDE announced Nov 2025 alongside Gemini 3. Born from Google's $2.4B acquisition of the Windsurf team, it introduces an 'agent-first' paradigm where AI agents function as independent actors capable of navigating an entire project's lifecycle. Features Editor View for hands-on coding and Manager View (Mission Control) for orchestrating multiple agents.",
    whyGood: [
      "Agent-first design — AI agents work as independent actors across the project",
      "Manager View (Mission Control) for spawning and observing multiple agents",
      "Trust-Building Artifacts for verifiable agent reasoning and plans",
      "Long-term memory that persists project context across sessions",
      "MCP integration for databases, APIs, docs, and scraping tools",
      "Multi-model support including Claude Sonnet 4.5 and GPT-OSS-120B",
    ],
    useCases: [
      "Full-stack application development with autonomous agents",
      "Orchestrating multi-agent teams for parallel feature development",
      "Complex refactoring with verifiable AI-generated implementation plans",
      "Project architecture and planning at a task-oriented level",
      "Enterprise development with SSO and data residency controls",
    ],
    tags: ["IDE", "Google", "Gemini 3", "Agent-first", "VS Code Fork"],
    stars: "N/A (Preview)",
    pricing: "Free preview; Pro ~$20/mo expected",
    lastUpdated: "Feb 2026",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: "coding-assistant",
    rating: 4.5,
    trending: false,
    url: "https://github.com/features/copilot",
    tagline: "The most widely adopted AI coding assistant with 1.8M+ subscribers",
    description:
      "GitHub Copilot remains the market leader in AI coding assistance with over 1.8 million paying subscribers. It supports multiple models including OpenAI, Claude, Gemini, and DeepSeek. The 2026 update introduced Next Edit Predictions that anticipate ripple effects across projects and suggest connected edits across the entire codebase.",
    whyGood: [
      "Largest user base and ecosystem with proven reliability",
      "Multi-model support (OpenAI, Claude, Gemini, DeepSeek)",
      "Next Edit Predictions for cross-file impact analysis",
      "Copilot Workspace for multi-file changes",
      "Deep GitHub workflow integration (PRs, Issues, Actions)",
      "Affordable at $10/month for individuals",
    ],
    useCases: [
      "Inline code completions predicting multiple lines",
      "Code explanation and fixing via Copilot Chat",
      "Multi-file changes with Copilot Workspace",
      "Pull request summaries and review assistance",
      "Learning new languages and frameworks quickly",
    ],
    tags: ["IDE Plugin", "GitHub", "Multi-model", "Enterprise"],
    stars: "N/A",
    pricing: "Free (2k completions/mo) / $10/mo / $39/user/mo",
    lastUpdated: "Jan 2026",
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "coding-assistant",
    rating: 4.7,
    trending: true,
    url: "https://cursor.sh",
    tagline: "AI-native IDE with best-in-class multi-file editing",
    description:
      "Cursor has rapidly become the preferred IDE for developers who want AI woven into every part of their workflow. Built as a VS Code fork, it provides whole-codebase context awareness. Its Composer mode enables sophisticated multi-file generation and refactoring that outperforms competitors on complex projects.",
    whyGood: [
      "Best-in-class Composer mode for multi-file generation",
      "Whole-repository context awareness — understands your entire codebase",
      "Tab completion that predicts edits based on full project context",
      "Cmd+K inline editing for rapid code transformation",
      "Built-in multi-model support for flexibility",
      "Familiar VS Code interface with minimal learning curve",
    ],
    useCases: [
      "Complex multi-file refactoring across large codebases",
      "Rapid prototyping with whole-project AI generation",
      "Architecture-level code transformations",
      "Exploring and understanding unfamiliar codebases",
      "Pair programming with context-aware AI agent",
    ],
    tags: ["IDE", "VS Code Fork", "Multi-model", "Composer"],
    stars: "N/A",
    pricing: "Free (limited) / Pro $20/mo / Business $40/user/mo",
    lastUpdated: "Feb 2026",
  },
  {
    id: "windsurf",
    name: "Windsurf (Cognition)",
    category: "coding-assistant",
    rating: 4.2,
    trending: false,
    url: "https://windsurf.com",
    tagline: "Agentic IDE with Cascade — acquired by Cognition (Devin AI)",
    description:
      "Windsurf is an agentic IDE originally from Codeium, now owned by Cognition (the Devin AI team) after a July 2025 acquisition. Features Cascade for multi-file edits and Flows for maintaining long development session context. Undercuts Cursor at $15/mo but faces uncertainty around its long-term roadmap after leadership changes.",
    whyGood: [
      "Cascade agent for multi-file edits with deep context awareness",
      "Flows maintain context over long development sessions",
      "More affordable than Cursor at $15/month",
      "Clean developer experience for multi-file editing",
      "Acts like a pair programmer that remembers your history",
    ],
    useCases: [
      "Solo development with persistent AI pair programming",
      "Budget-conscious teams wanting agentic coding",
      "Multi-file editing and iterative problem-solving",
      "Rapid prototyping with AI-driven context awareness",
    ],
    tags: ["IDE", "VS Code Fork", "Cascade", "Cognition"],
    stars: "N/A",
    pricing: "Free (25 credits/mo) / $15/mo / $30/user/mo",
    lastUpdated: "Jan 2026",
  },
  {
    id: "cline",
    name: "Cline",
    category: "cli-tool",
    rating: 4.4,
    trending: true,
    url: "https://github.com/cline/cline",
    tagline: "Open-source autonomous coding agent — BYO API key, full control",
    description:
      "Cline is a free, open-source AI coding assistant that runs in VS Code. It uses a bring-your-own API key model, giving developers full control over costs and model selection. Best for open-source purists who want a powerful agentic coding experience without vendor lock-in.",
    whyGood: [
      "Completely free and open source",
      "Bring-your-own API key for full cost and model control",
      "Runs autonomous multi-step coding tasks",
      "No vendor lock-in — use any compatible LLM provider",
      "Active open-source community and rapid development",
    ],
    useCases: [
      "Autonomous code generation with custom model selection",
      "Budget-conscious development with pay-per-use API pricing",
      "Open-source projects requiring transparent AI tooling",
      "Custom workflows and integrations via extensible architecture",
    ],
    tags: ["VS Code", "Open Source", "BYO Key", "Autonomous"],
    stars: "35k+",
    pricing: "Free (BYO API key)",
    lastUpdated: "Feb 2026",
  },

  // ── Agent Frameworks ──
  {
    id: "langchain",
    name: "LangChain / LangGraph",
    category: "agent-framework",
    rating: 4.6,
    trending: false,
    url: "https://github.com/langchain-ai/langchain",
    tagline: "The most recognized LLM orchestration framework with 80K+ stars",
    description:
      "LangChain is the most widely adopted agent framework in the LLM ecosystem. Originally built for prompt chaining, it evolved into a full orchestration layer for LLM-powered applications. LangGraph adds graph-first thinking for stateful, multi-step workflows with nodes, edges, and conditional routing — enabling traceable, debuggable agent flows.",
    whyGood: [
      "Largest community with 80K+ GitHub stars and comprehensive docs",
      "Modular architecture for building complex LLM pipelines",
      "LangGraph enables graph-based stateful workflows",
      "Proven enterprise adoption and extensive integrations",
      "Traceable, debuggable flows for production-grade agents",
      "Rich ecosystem of tools, retrievers, and memory modules",
    ],
    useCases: [
      "Building complex multi-step RAG pipelines",
      "Stateful workflow orchestration with conditional routing",
      "Enterprise chatbots with tool use and memory",
      "Data retrieval and processing chains",
      "Production-grade agent deployments with monitoring",
    ],
    tags: ["Python", "TypeScript", "Graph", "RAG", "Enterprise"],
    stars: "80k+",
    pricing: "Open source / LangSmith hosted plans",
    lastUpdated: "Feb 2026",
  },
  {
    id: "crewai",
    name: "CrewAI",
    category: "agent-framework",
    rating: 4.5,
    trending: true,
    url: "https://github.com/crewAIInc/crewAI",
    tagline: "Role-based multi-agent collaboration with Crews and Flows",
    description:
      "CrewAI emphasizes role-based multi-agent systems where each agent has a specialized function within a team. Uses a two-layer architecture: Crews for dynamic role-based collaboration and Flows for deterministic event-driven orchestration. Gentler learning curve makes it ideal for rapid prototyping and mid-scale agent setups.",
    whyGood: [
      "Intuitive role-based agent design mimicking real teams",
      "Two-layer architecture (Crews + Flows) balances autonomy with control",
      "Gentler learning curve than LangChain for beginners",
      "Great for rapid prototyping of multi-agent systems",
      "Natural task delegation and negotiation between agents",
      "Growing ecosystem with 20K+ GitHub stars",
    ],
    useCases: [
      "Multi-agent research and analysis teams",
      "Content generation pipelines with specialized roles",
      "Automated business workflow orchestration",
      "Rapid prototyping of collaborative AI systems",
      "Customer support with specialized agent roles",
    ],
    tags: ["Python", "Multi-agent", "Role-based", "Crews"],
    stars: "20k+",
    pricing: "Open source / Enterprise plans",
    lastUpdated: "Jan 2026",
  },
  {
    id: "autogen",
    name: "Microsoft AutoGen",
    category: "agent-framework",
    rating: 4.4,
    trending: false,
    url: "https://github.com/microsoft/autogen",
    tagline: "Multi-agent conversations with strong Microsoft ecosystem integration",
    description:
      "Microsoft AutoGen supports next-generation LLM applications through multi-agent conversations. It treats workflows as conversations between agents, making it natural for collaborative AI systems. Particularly strong for organizations in the Microsoft/Azure ecosystem with excellent performance on coding tasks.",
    whyGood: [
      "Intuitive multi-agent conversation paradigm",
      "Strong Microsoft/Azure ecosystem integration",
      "Excellent performance on collaborative coding tasks",
      "Supports complex negotiation between agents",
      "Well-suited for enterprise environments",
      "Active development backed by Microsoft Research",
    ],
    useCases: [
      "Collaborative code generation with multiple specialized agents",
      "Enterprise workflows in the Microsoft/Azure ecosystem",
      "Research and analysis requiring multi-perspective reasoning",
      "Automated testing and code review pipelines",
      "Complex problem-solving through agent debates",
    ],
    tags: ["Python", "Microsoft", "Multi-agent", "Conversations"],
    stars: "40k+",
    pricing: "Open source",
    lastUpdated: "Jan 2026",
  },

  // ── AI Platforms ──
  {
    id: "openai-platform",
    name: "OpenAI Platform (GPT-5)",
    category: "ai-platform",
    rating: 4.6,
    trending: true,
    url: "https://platform.openai.com",
    tagline: "Industry-leading AI platform with GPT-5 and Agents SDK",
    description:
      "The OpenAI Platform provides access to GPT-5 and a comprehensive suite of developer tools. The Agents SDK enables building production-ready AI agents with built-in tool use, function calling, and structured outputs. Remains the most widely used commercial AI API with deep ecosystem support.",
    whyGood: [
      "GPT-5 delivers state-of-the-art language understanding",
      "Agents SDK for building production-ready AI agents",
      "Largest ecosystem of third-party integrations",
      "Structured outputs and reliable function calling",
      "Comprehensive API with vision, audio, and embedding models",
      "Strong enterprise features with data privacy controls",
    ],
    useCases: [
      "Building AI-powered SaaS applications",
      "Production agent deployments with function calling",
      "Content generation and analysis at scale",
      "Multi-modal applications (text, vision, audio)",
      "Enterprise knowledge management and search",
    ],
    tags: ["API", "GPT-5", "Agents SDK", "Multi-modal"],
    stars: "N/A",
    pricing: "Pay-per-use API / ChatGPT Pro $200/mo",
    lastUpdated: "Feb 2026",
  },
  {
    id: "anthropic-api",
    name: "Anthropic Claude API",
    category: "ai-platform",
    rating: 4.7,
    trending: true,
    url: "https://platform.claude.com",
    tagline: "Claude Opus 4.6 — top model for coding, agents, and safety",
    description:
      "The Anthropic Claude API provides access to Claude Opus 4.6 (the 'best model for coding, agents, and computer use'), Sonnet, and Haiku models. Known for strong safety alignment, extended thinking, and exceptional performance on coding and agentic tasks. The Claude Agent SDK enables building custom agent workflows.",
    whyGood: [
      "Claude Opus 4.6 excels at coding and agentic tasks",
      "Extended thinking mode for complex reasoning",
      "Industry-leading safety and alignment",
      "200K context window for processing large codebases",
      "Claude Agent SDK for custom multi-agent systems",
      "MCP (Model Context Protocol) for rich tool integration",
    ],
    useCases: [
      "AI-powered coding assistants and code generation",
      "Complex document analysis with long context",
      "Building safe, aligned AI agents for enterprise",
      "Research and analysis requiring deep reasoning",
      "Custom development workflows via Claude Code",
    ],
    tags: ["API", "Claude", "Safety", "MCP", "Extended Thinking"],
    stars: "N/A",
    pricing: "Pay-per-use API / Claude Pro $20/mo",
    lastUpdated: "Feb 2026",
  },

  // ── GitHub Projects ──
  {
    id: "n8n",
    name: "n8n",
    category: "github-project",
    rating: 4.5,
    trending: true,
    url: "https://github.com/n8n-io/n8n",
    tagline: "Open-source workflow automation with native AI capabilities",
    description:
      "n8n is an open-source workflow automation platform combining a visual no-code interface with code flexibility, now supercharged with native AI capabilities. With 400+ integrations, it enables technical teams to build powerful automation pipelines with full control over data and execution.",
    whyGood: [
      "Visual no-code interface combined with full code flexibility",
      "400+ native integrations for seamless connectivity",
      "Native AI nodes for LLM-powered automation",
      "Self-hostable for full data control and privacy",
      "Active community and rapid feature development",
    ],
    useCases: [
      "AI-powered automation workflows and pipelines",
      "Data processing and ETL with AI enrichment",
      "Building internal tools with AI decision-making",
      "Customer support automation with LLM integration",
      "DevOps and CI/CD automation with AI triggers",
    ],
    tags: ["Automation", "No-code", "Self-hosted", "AI Workflows"],
    stars: "55k+",
    pricing: "Open source / Cloud plans from $20/mo",
    lastUpdated: "Feb 2026",
  },
  {
    id: "ragflow",
    name: "RAGFlow",
    category: "github-project",
    rating: 4.3,
    trending: true,
    url: "https://github.com/infiniflow/ragflow",
    tagline: "Open-source RAG engine fusing retrieval with agent capabilities",
    description:
      "RAGFlow is an open-source engine for Retrieval-Augmented Generation that fuses cutting-edge RAG with agent capabilities to create a superior context layer for LLMs. Provides deep document understanding, template-based chunking, and grounded citations to reduce hallucinations.",
    whyGood: [
      "Deep document understanding with template-based chunking",
      "Grounded citations to reduce LLM hallucinations",
      "Combines RAG with agent capabilities seamlessly",
      "Supports multiple document formats and data sources",
      "Active development with growing community",
    ],
    useCases: [
      "Enterprise knowledge base with grounded AI answers",
      "Document Q&A systems with citation tracking",
      "Building RAG pipelines with agent orchestration",
      "Legal and compliance document analysis",
      "Research paper analysis and summarization",
    ],
    tags: ["RAG", "Open Source", "Document AI", "Knowledge Base"],
    stars: "35k+",
    pricing: "Open source",
    lastUpdated: "Jan 2026",
  },
  {
    id: "opencode",
    name: "OpenCode",
    category: "github-project",
    rating: 4.4,
    trending: true,
    url: "https://github.com/opencode-ai/opencode",
    tagline: "The open-source coding agent with 100K+ GitHub stars",
    description:
      "OpenCode is a fully open-source coding agent that has rapidly accumulated over 100K GitHub stars. It provides a transparent, community-driven alternative to proprietary coding assistants, with support for multiple LLM backends and extensible architecture.",
    whyGood: [
      "Fully open source with massive community (100K+ stars)",
      "Transparent AI coding with community-driven development",
      "Multi-model backend support for flexibility",
      "Extensible plugin and tool architecture",
      "No vendor lock-in or subscription costs",
    ],
    useCases: [
      "Open-source alternative to proprietary coding assistants",
      "Custom coding agent workflows with full control",
      "Community-driven AI development tools",
      "Educational use for understanding AI coding agents",
    ],
    tags: ["Open Source", "Coding Agent", "Community", "Multi-model"],
    stars: "105k+",
    pricing: "Open source (BYO API key)",
    lastUpdated: "Feb 2026",
  },
  {
    id: "langflow",
    name: "Langflow",
    category: "github-project",
    rating: 4.3,
    trending: false,
    url: "https://github.com/langflow-ai/langflow",
    tagline: "Visual low-code builder for agentic and RAG applications",
    description:
      "Langflow is a powerful visual tool for building and deploying AI-powered agents and workflows. Its drag-and-drop interface makes it accessible to non-developers while retaining the power needed for production deployments. Supports integration with major LLM providers and tool ecosystems.",
    whyGood: [
      "Visual drag-and-drop interface for building AI workflows",
      "Accessible to non-developers while remaining powerful",
      "Integrates with major LLM providers and tools",
      "Export flows as production-ready Python code",
      "Large community with 140K+ stars",
    ],
    useCases: [
      "Rapid prototyping of AI agent workflows",
      "Building RAG pipelines without code",
      "Deploying AI-powered chatbots and assistants",
      "Teaching AI concepts with visual workflow builder",
      "Connecting multiple AI services in unified workflows",
    ],
    tags: ["Low-code", "Visual Builder", "RAG", "Workflows"],
    stars: "144k+",
    pricing: "Open source / DataStax hosted plans",
    lastUpdated: "Jan 2026",
  },

  // ── Skills & Learning ──
  {
    id: "gen-ai-beginners",
    name: "Generative AI for Beginners",
    category: "skill",
    rating: 4.6,
    trending: false,
    url: "https://github.com/microsoft/generative-ai-for-beginners",
    tagline: "Microsoft's 21-lesson course for building with generative AI",
    description:
      "Microsoft's comprehensive educational repository offers 21 lessons covering everything from prompt engineering to building full AI applications. With over 106K GitHub stars, it's one of the most popular resources for developers getting started with generative AI.",
    whyGood: [
      "Structured 21-lesson curriculum from basic to advanced",
      "Backed by Microsoft with regular updates",
      "Hands-on projects and coding exercises",
      "Covers prompt engineering, RAG, agents, and deployment",
      "Free and open source — no paywall",
      "106K+ GitHub stars showing community trust",
    ],
    useCases: [
      "Onboarding developers into the AI ecosystem",
      "Learning prompt engineering and AI fundamentals",
      "Building first AI applications with guided projects",
      "Team training programs for AI adoption",
      "Self-paced learning for career transition into AI",
    ],
    tags: ["Education", "Microsoft", "Free", "Beginner-friendly"],
    stars: "106k+",
    pricing: "Free",
    lastUpdated: "Jan 2026",
  },
  {
    id: "prompt-engineering",
    name: "Prompt Engineering Guide",
    category: "skill",
    rating: 4.5,
    trending: false,
    url: "https://github.com/dair-ai/Prompt-Engineering-Guide",
    tagline: "Comprehensive guide to prompt engineering techniques and best practices",
    description:
      "The most comprehensive open-source guide to prompt engineering. Covers techniques from basic zero-shot prompting to advanced chain-of-thought, tree-of-thought, and ReAct patterns. Essential reading for anyone working with LLMs professionally.",
    whyGood: [
      "Most comprehensive prompt engineering resource available",
      "Covers basic to advanced techniques systematically",
      "Regularly updated with latest research and methods",
      "Community-contributed examples and patterns",
      "Available in multiple languages",
    ],
    useCases: [
      "Mastering prompt engineering for production AI systems",
      "Learning chain-of-thought and ReAct patterns",
      "Optimizing LLM outputs for specific use cases",
      "Training teams on effective AI communication",
      "Reference guide for advanced prompting techniques",
    ],
    tags: ["Education", "Prompting", "LLM", "Open Source"],
    stars: "55k+",
    pricing: "Free",
    lastUpdated: "Dec 2025",
  },
  {
    id: "mcp-protocol",
    name: "Model Context Protocol (MCP)",
    category: "skill",
    rating: 4.6,
    trending: true,
    url: "https://modelcontextprotocol.io",
    tagline: "Open standard for connecting AI models to data and tools",
    description:
      "The Model Context Protocol (MCP) is an open standard pioneered by Anthropic for connecting AI models to external data sources, APIs, and tools. Rapidly adopted across the industry — supported by Claude Code, Google Antigravity, Cursor, and others. Essential skill for building production AI systems in 2026.",
    whyGood: [
      "Open standard with broad industry adoption",
      "Enables AI models to interact with any data source or tool",
      "Supported by major platforms (Claude, Antigravity, Cursor)",
      "Reduces integration complexity for AI applications",
      "Active development with growing server ecosystem",
      "Critical skill for AI developers in 2026",
    ],
    useCases: [
      "Connecting AI assistants to databases and APIs",
      "Building tool-using AI agents with standardized interfaces",
      "Enterprise data integration for AI systems",
      "Creating reusable MCP servers for common services",
      "Enabling AI to interact with browsers, files, and cloud services",
    ],
    tags: ["Protocol", "Integration", "Anthropic", "Open Standard"],
    stars: "45k+",
    pricing: "Free / Open standard",
    lastUpdated: "Feb 2026",
  },
];
